apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yellowhorrorhose-game
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - yellowhorrorhose.20-223-11-235.sslip.io
    secretName: yellowhorrorhose-tls
  rules:
  - host: yellowhorrorhose.20-223-11-235.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: yellowhorrorhose-game
            port:
              number: 80
